[workspace]
members = [
    "bencher",
    "harness",
    "programs/*",
    "test-programs/*",
]
resolver = "2"

[workspace.package]
authors = ["Joe Caulfield <jcaulfield135@gmail.com>"]
repository = "https://github.com/buffalojoec/mollusk"
readme = "README.md"
license = "MIT"
edition = "2021"
version = "0.0.9-solana-1.18"

[workspace.dependencies]
bincode = "1.3.3"
bs58 = "0.5.1"
mollusk-svm = { path = "harness", version = "0.0.9-solana-1.18" }
mollusk-svm-bencher = { path = "bencher", version = "0.0.9-solana-1.18" }
mollusk-svm-programs-memo = { path = "programs/memo", version = "0.0.9-solana-1.18" }
mollusk-svm-programs-token = { path = "programs/token", version = "0.0.9-solana-1.18" }
num-format = "0.4.4"
prost = "0.10"
prost-build = "0.10"
prost-types = "0.10"
serde = "1.0.203"
serde_json = "1.0.117"
solana-bpf-loader-program = "1.18"
solana-logger = "1.18"
solana-program = "1.18"
solana-program-runtime = "1.18"
solana-stake-program = "1.18"
solana-system-program = "1.18"
solana-sdk = "1.18"
thiserror = "1.0.64"
